### ISSUE TITLE
Wrong file name

### ISSUE THREAD

**Issue by neliudochka** [AKushch1337/Bookish#5]
You renamed fun ItemBookList() to LibraryItem(), but you didn't rename the file it is written in.
![Screenshot from 2023-06-06 12-08-41](https://github.com/AKushch1337/Bookish/assets/90915275/f05734f3-e6b0-42eb-b1bb-cdda8ebae21b)
Renamed it, please

**Comment by AKushch1337** [comment]
Good catch, thanks!

**Comment by AKushch1337** [comment]
Fixed!

**Comment by neliudochka** [comment]
good, Monseigneur, good...
